spring:
  application:
    name: ecommerce
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: cheonkyu
    password: cheonkyu
  jpa:
    properties:
      hibernate.jdbc.batch_size: 20
      hibernate.cache.use_query_cache: false
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_structured_entries: false
      hibernate.cache.use_minimal_puts: false
      hibernate.dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: true
    hibernate:
      ddl-auto: create-drop	# ?????? validate
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#      use-new-id-generator-mappings: false
      dialect: org.hibernate.dialect.MySQLDialect
    show_sql: true  # sql ??? ?????.
    format_sql: true  # sql query formatting
    use_sql_comments: true  # sql ??? ????? ?????.

logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql: trace